import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/header/header";
import Footer from "@/components/layouts/footer/footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
